### ISSUE TITLE
doubt in paper regarding LENGTH token

### ISSUE THREAD

**Issue by thevasudevgupta** [lemmonation/abnet#4]
Hi,

Really nice paper. I was trying to reproduce this paper.

I would like to know how you are initialising embedding for [LENGTH] token (whether randomly initializing)? If randomly, then how are you training it since bert is freezed throughout (and hence embedding layer)? 

Thanks

**Comment by lemmonation** [comment]
Thanks for your interest!

The length embedding is randomly initialized, which is decoupled from bert embeddings. Please see [this line](https://github.com/lemmonation/abnet/blob/main/bert/modeling.py#L791) and [this line](https://github.com/lemmonation/abnet/blob/main/train.py#L63).

**Comment by thevasudevgupta** [comment]
Thanks. Got it.
